// Per-repo integrations: ignores, .mcp.json, Claude/Windsurf, git hooks, remerge helper.
import { existsSync, readFileSync, writeFileSync, copyFileSync, unlinkSync, rmdirSync, chmodSync, appendFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import {
    TEMPLATES_DIR, LOCAL_BIN, GROUPS_DIR, IS_WIN,
    ensureDir, readJson, writeJson, log, run, runOrThrow, graphifyPython,
} from './util.js';

const STACK_TEMPLATES = ['react-native', 'python', 'node', 'go', 'generic'];

export function writeGraphifyignore(repo, stack) {
    const dst = join(repo, '.graphifyignore');
    if (existsSync(dst)) { log.info('.graphifyignore already exists, leaving as-is'); return; }
    const tplName = STACK_TEMPLATES.includes(stack) ? stack : 'generic';
    const src = join(TEMPLATES_DIR, `graphifyignore-${tplName}.txt`);
    copyFileSync(src, dst);
    log.info(`.graphifyignore written (${tplName} template)`);
}

export function updateGitignore(repo) {
    const f = join(repo, '.gitignore');
    const existing = existsSync(f) ? readFileSync(f, 'utf8') : '';
    if (existing.includes('graphify-out/wiki/')) return;
    const block = '\n# graphify-fleet\ngraphify-out/wiki/\ngraphify-out/manifest.json\ngraphify-out/cost.json\ngraphify-out/cache/\n';
    writeFileSync(f, existing + block);
    log.info('.gitignore updated');
}

export function writeMcpJson(repo, groupGraph) {
    const f = join(repo, '.mcp.json');
    const py = graphifyPython();
    const server = { command: py, args: ['-m', 'graphify.serve', groupGraph] };
    const obj = existsSync(f) ? readJson(f) : { mcpServers: {} };
    obj.mcpServers = { ...(obj.mcpServers ?? {}), graphify: server };
    writeJson(f, obj);
    log.info(`.mcp.json: graphify -> ${groupGraph}`);
}

export function installClaudeSkill(repo) {
    const r = run('graphify', ['claude', 'install'], { cwd: repo });
    if (r.code === 0) log.info('claude skill installed (CLAUDE.md + PreToolUse hook)');
    else log.warn('graphify claude install failed (continuing)');
}

const WINDSURF_WORKFLOW_TEMPLATE = join(TEMPLATES_DIR, 'windsurf-workflow.md');

export function writeWindsurfFiles(repo, group, groupGraph) {
    const wf = join(repo, '.windsurf', 'workflows');
    ensureDir(wf);
    copyFileSync(WINDSURF_WORKFLOW_TEMPLATE, join(wf, 'graphify.md'));
    const rules = join(repo, '.windsurfrules');
    const cur = existsSync(rules) ? readFileSync(rules, 'utf8') : '';
    if (cur.includes('## graphify')) { log.info('windsurf rules already present, leaving as-is'); return; }
    const block = `

## graphify

This project is part of the **${group}** group, with a merged knowledge graph at ${groupGraph}.

Rules:
- Before answering architecture or codebase questions, read graphify-out/GRAPH_REPORT.md for god nodes and community structure
- If graphify-out/wiki/index.md exists, navigate it instead of reading raw files
- For cross-repo questions, query the graphify MCP server (group: ${group}) which exposes the merged graph
- After modifying code in this session, run \`graphify update .\` to keep the graph current
`;
    writeFileSync(rules, cur + block);
    log.info('windsurf workflow + rules written');
}

export function writeRemergeHelper(group, groupGraph, repos) {
    ensureDir(LOCAL_BIN);
    ensureDir(GROUPS_DIR);
    const helperPath = join(LOCAL_BIN, IS_WIN ? `graphify-fleet-merge-${group}.ps1` : `graphify-fleet-merge-${group}`);
    const graphs = repos.map(r => join(r.path, 'graphify-out', 'graph.json'));

    if (IS_WIN) {
        const list = graphs.map(g => `'${g.replace(/'/g, "''")}'`).join(',');
        const ps = `# auto-generated by gfleet — re-merge group '${group}'
$ErrorActionPreference = 'SilentlyContinue'
Start-Sleep -Seconds 3
$graphs = @(${list})
$existing = $graphs | Where-Object { Test-Path $_ }
if ($existing.Count -ge 2) {
    & graphify merge-graphs $existing --out '${groupGraph}' | Out-Null
} elseif ($existing.Count -eq 1) {
    Copy-Item $existing[0] '${groupGraph}' -Force
}
`;
        writeFileSync(helperPath, ps);
    } else {
        const arrayLines = graphs.map(g => `GRAPHS+=("${g.replace(/"/g, '\\"')}")`).join('\n');
        const sh = `#!/usr/bin/env bash
# auto-generated by gfleet — re-merge group '${group}'
set -e
GROUP_GRAPH="${groupGraph}"
GRAPHS=()
${arrayLines}
sleep 3
EXISTING=()
for g in "\${GRAPHS[@]}"; do [ -f "$g" ] && EXISTING+=("$g"); done
if [ "\${#EXISTING[@]}" -ge 2 ]; then
    graphify merge-graphs "\${EXISTING[@]}" --out "$GROUP_GRAPH" >/dev/null 2>&1 || true
elif [ "\${#EXISTING[@]}" -eq 1 ]; then
    cp "\${EXISTING[0]}" "$GROUP_GRAPH"
fi
`;
        writeFileSync(helperPath, sh);
        chmodSync(helperPath, 0o755);
    }
    return helperPath;
}

const HOOK_NAMES = ['post-commit', 'post-checkout'];

export function installGitHooks(repo, group, helperPath) {
    const r = run('graphify', ['hook', 'install'], { cwd: repo });
    if (r.code !== 0) log.warn('graphify hook install failed (continuing)');
    for (const name of HOOK_NAMES) {
        const f = join(repo, '.git', 'hooks', name);
        if (!existsSync(f)) continue;
        const cur = readFileSync(f, 'utf8');
        if (cur.includes(`gfleet-start (${group})`)) continue;
        const block = IS_WIN
            ? `\n# gfleet-start (${group})\npwsh -NoProfile -File "${helperPath}" 2>$null &\n# gfleet-end (${group})\n`
            : `\n# gfleet-start (${group})\nnohup "${helperPath}" > /dev/null 2>&1 &\ndisown 2>/dev/null || true\n# gfleet-end (${group})\n`;
        appendFileSync(f, block);
        chmodSync(f, 0o755);
    }
    log.info('git hooks installed (+ group remerge)');
}

export function removeGitHooks(repo, group) {
    for (const name of HOOK_NAMES) {
        const f = join(repo, '.git', 'hooks', name);
        if (!existsSync(f)) continue;
        const cur = readFileSync(f, 'utf8');
        const re = new RegExp(`\\n?# gfleet-start \\(${group}\\)[\\s\\S]*?# gfleet-end \\(${group}\\)\\n?`, 'g');
        const cleaned = cur.replace(re, '');
        if (cleaned !== cur) writeFileSync(f, cleaned);
    }
}

export function removeMcpEntry(repo) {
    const f = join(repo, '.mcp.json');
    if (!existsSync(f)) return;
    const obj = readJson(f);
    if (!obj.mcpServers?.graphify) return;
    delete obj.mcpServers.graphify;
    if (Object.keys(obj.mcpServers).length === 0) {
        try { unlinkSync(f); log.info('.mcp.json removed (was empty)'); } catch {}
    } else {
        writeJson(f, obj);
        log.info('.mcp.json: graphify entry removed');
    }
}

export function removeWindsurfFiles(repo) {
    const wf = join(repo, '.windsurf', 'workflows', 'graphify.md');
    try { unlinkSync(wf); } catch {}
    try { rmdirSync(join(repo, '.windsurf', 'workflows')); } catch {}
    try { rmdirSync(join(repo, '.windsurf')); } catch {}
    const rules = join(repo, '.windsurfrules');
    if (!existsSync(rules)) return;
    const cur = readFileSync(rules, 'utf8');
    const cleaned = cur.replace(/\n*## graphify\n[\s\S]*?(?=\n## |\n*$)/, '');
    if (cleaned !== cur) writeFileSync(rules, cleaned);
}

// Global Windsurf MCP entry (one per group, named graphify-<group>)
const WINDSURF_MCP = join(process.env.HOME ?? '', '.codeium', 'windsurf', 'mcp_config.json');

export function addWindsurfGlobalMcp(group, groupGraph) {
    ensureDir(dirname(WINDSURF_MCP));
    const obj = existsSync(WINDSURF_MCP) ? readJson(WINDSURF_MCP) : {};
    obj.mcpServers = obj.mcpServers ?? {};
    obj.mcpServers[`graphify-${group}`] = {
        command: graphifyPython(),
        args: ['-m', 'graphify.serve', groupGraph],
    };
    writeJson(WINDSURF_MCP, obj);
    log.info(`windsurf MCP entry: graphify-${group}`);
}

export function removeWindsurfGlobalMcp(group) {
    if (!existsSync(WINDSURF_MCP)) return;
    const obj = readJson(WINDSURF_MCP);
    if (obj.mcpServers?.[`graphify-${group}`]) {
        delete obj.mcpServers[`graphify-${group}`];
        writeJson(WINDSURF_MCP, obj);
    }
}

const WINDSURF_SKILL_DST = join(process.env.HOME ?? '', '.codeium', 'windsurf', 'skills', 'graphify', 'SKILL.md');
const WINDSURF_SKILL_URL = 'https://raw.githubusercontent.com/safishamsi/graphify/7c77a891939f889b99b48c0e8bc8cee5546a4c72/graphify/skill-windsurf.md';

export async function ensureWindsurfSkill() {
    if (existsSync(WINDSURF_SKILL_DST)) return;
    ensureDir(dirname(WINDSURF_SKILL_DST));
    try {
        const r = await fetch(WINDSURF_SKILL_URL);
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        const text = await r.text();
        writeFileSync(WINDSURF_SKILL_DST, text);
        log.info('windsurf SKILL.md installed (from PR #574)');
    } catch (e) {
        log.warn(`could not fetch windsurf SKILL.md: ${e.message}`);
    }
}
